services:
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # DATABASE_URL: "${DATABASE_URL?:error}"
      DATABASE_URL: "postgres://postgres:secret@db:5432/db"
      BETTER_AUTH_SECRET: "${BETTER_AUTH_SECRET:?error}"
      BETTER_AUTH_URL: "${BETTER_AUTH_URL:?error}"
    ports:
      - 3000:3000
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  db-data:
