services:
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=db
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:${SERVICE_PASSWORD_POSTGRES}@db:5432/db
      - BETTER_AUTH_SECRET=${SERVICE_PASSWORD_64_BETTER_AUTH}
      - BETTER_AUTH_URL=${SERVICE_FQDN_APP}
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  db-data:
